//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.RobotServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotServiceReference.IRobotService")]
    public interface IRobotService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadMessage) of message FileUploadMessage does not match the default value (InitInversion)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/InitInversion", ReplyAction="http://tempuri.org/IRobotService/InitInversionResponse")]
        TestClient.RobotServiceReference.GuidMessage InitInversion(TestClient.RobotServiceReference.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/StartInversion", ReplyAction="http://tempuri.org/IRobotService/StartInversionResponse")]
        bool StartInversion(System.Guid ownerId, System.Guid inversionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/StopInversion", ReplyAction="http://tempuri.org/IRobotService/StopInversionResponse")]
        bool StopInversion(System.Guid ownerId, System.Guid inversionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/QueryInversion", ReplyAction="http://tempuri.org/IRobotService/QueryInversionResponse")]
        int QueryInversion(System.Guid wellId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/RetrieveInversion", ReplyAction="http://tempuri.org/IRobotService/RetrieveInversionResponse")]
        byte[] RetrieveInversion(System.Guid userId, System.Guid inversionId, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotService/GetData", ReplyAction="http://tempuri.org/IRobotService/GetDataResponse")]
        string GetData(int value);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileData;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(string FileName, System.IO.Stream FileData) {
            this.FileName = FileName;
            this.FileData = FileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuidMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuidMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid InversionId;
        
        public GuidMessage() {
        }
        
        public GuidMessage(System.Guid InversionId) {
            this.InversionId = InversionId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotServiceChannel : TestClient.RobotServiceReference.IRobotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotServiceClient : System.ServiceModel.ClientBase<TestClient.RobotServiceReference.IRobotService>, TestClient.RobotServiceReference.IRobotService {
        
        public RobotServiceClient() {
        }
        
        public RobotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RobotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.RobotServiceReference.GuidMessage TestClient.RobotServiceReference.IRobotService.InitInversion(TestClient.RobotServiceReference.FileUploadMessage request) {
            return base.Channel.InitInversion(request);
        }
        
        public System.Guid InitInversion(string FileName, System.IO.Stream FileData) {
            TestClient.RobotServiceReference.FileUploadMessage inValue = new TestClient.RobotServiceReference.FileUploadMessage();
            inValue.FileName = FileName;
            inValue.FileData = FileData;
            TestClient.RobotServiceReference.GuidMessage retVal = ((TestClient.RobotServiceReference.IRobotService)(this)).InitInversion(inValue);
            return retVal.InversionId;
        }
        
        public bool StartInversion(System.Guid ownerId, System.Guid inversionId) {
            return base.Channel.StartInversion(ownerId, inversionId);
        }
        
        public bool StopInversion(System.Guid ownerId, System.Guid inversionId) {
            return base.Channel.StopInversion(ownerId, inversionId);
        }
        
        public int QueryInversion(System.Guid wellId) {
            return base.Channel.QueryInversion(wellId);
        }
        
        public byte[] RetrieveInversion(System.Guid userId, System.Guid inversionId, string accessCode) {
            return base.Channel.RetrieveInversion(userId, inversionId, accessCode);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
    }
}
